stack/templates/_helpers.tpl, stack/templates/deployment.yaml
Adds support for `tcpSocket` container probes
The default values sets up `httpGet` probes and the default merging means configuring a `tcpSocket` probe puts both `httpGet` and `tcpSocket` keys in the probe sub-object. This leads to invalid Deployment K8s manifests, so we have to use the `omit` functionality of Helm to achieve desired manifest.
=> feat: add support for tcp probes

stack/templates/pvc.yaml
When defining more than one services, the rendered pvc manifests ends up containing two `---` lines which throws an error. This appears to fix the issue.
=> Fix pvc manifest

argus-config/templates/external_secrets_env.yaml
Terraform in argus-infra-stacks creates the ClusterExternalSecret resource which is used to make ExternalSecrets in all of the cluster. This PR fixes a bug where this helm chart was trying to overwrite the values in that ExternalSecret, causing conflicts and the argo application to show up in a not-synced state.
=> fix: terraform and helm fighting over which values to use

stack/templates/oidc_proxy.yaml, stack/tests/oidc_test.yaml, stack/values.yaml
This PR fixes a bug in the `extraArgs` values. Before, it was expected to be a map[string]string. However, many of the flags are non-unique, so being able to specify two identical flags twice wasn't possible. Changing it so that the extraArgs value is an array and the raw strings are injected as flags.
=> fix: make extra args an array

stack/templates/deployment.yaml, stack/values.yaml
This is needed to allow OTEL to retrieve spans from an application running in a different container; shareProcessNamespace will have to be set to `true`.
=> feat: Support shareProcessNamespace (defaults to false)

stack/templates/_helpers.tpl, stack/tests/ingress_test.yaml, stack/values.yaml
This oauth2_proxy can set headers on successful authentication response from the OIDC provider. Nginx uses the auth-url to trigger the oauth2_proxy, so it also needs to forward these headers. This PR changes the behavior of the helm chart tom by default, pass along the "Authorization" and "X-Forwarded-Email" headers and additionally allowing the user to add additional headers to pass along from the oauth2_proxy with `.Values.global.oidcProxy.additionalHeaders`.
* https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#external-authentication
=> fix: missing headers set by oauth2_proxy

stack/templates/_helpers.tpl, stack/tests/deployment_test.yaml
Allows users to change the names of their CRDs to not include random pet names.
=> fix: fullname override to work

stack/templates/oidc_proxy.yaml, stack/tests/oidc_test.yaml, stack/values.yaml
Allow for the oidc proxy containers to have volumes and volume mounts specified in their configuration. Helpful for when folks want to customize the HTML templates that are loaded for sign_in and sign_out.
=> feat: allow volumes and volume mounts in oidc proxy

stack/templates/_helpers.tpl, stack/templates/oidc_proxy.yaml, stack/tests/ingress_test.yaml, stack/tests/oidc_test.yaml
The ingress CRD for the oauth2_proxy was missing additional hosts that were specified in the configuration. This change combines all the hosts from the configuration that have `oidcProtected = true` to the list of oauth2_proxy hosts. 
Additionally, it changes the default route to sign in from the Argus URL at "/oauth2/start" to whatever domain you are currently on at "/oauth2/sign_in". Changing to whatever domain you are currently on allows support for logging in through a different domain other than the Argus domain (we don't want to redirect to a different domain like the pet name ones when we are on a production domain when logging in). 
The change to "/oauth2/sign_in" allows people to be able to display the oauth2 landing page if they want to enable it like they do in litqa agent. …
=> fix: add additional hosts to the oidc proxy ingress

stack/templates/ingress.yaml, stack/tests/ingress_test.yaml
This change splits the TLS sections of the ingress so that all *.czi.team domains reuse the cluster-wide TLS certificates. Custom hosts still will issue new certificates. This will help with development environments from blowing through our letsencrypt rate limit.
* https://github.com/chanzuckerberg/argus-infra-stacks/pull/204
=> feat: share wildcard certificate for czi.team domains

stack/templates/_helpers.tpl, stack/templates/ingress.yaml, stack/templates/oidc_proxy.yaml, stack/tests/ingress_test.yaml, stack/tests/oidc_test.yaml, stack/values.yaml
This PR changes the networking to remove all the custom nginx annotations. This simplifies our networking stack quite a bit. Now, if the service marked with oidcProtected = true, nginx will route the traffic through the oauth2_proxy. However, if oidcProtected = false, nginx will route the traffic directly to the service. Nginx is still in charge of terminating TLS. 
This fixes the bug where people weren't able to control the behavior of the proxy flags very well due to how we were only calling the oauth2_proxy from nginx using the `auth` directive. 
* Tested with https://github.com/chanzuckerberg/core-platform-example-app/pull/105
=> feat: conditional logic around the ingress point to the service or the oauth2 proxy service

stack/templates/_helpers.tpl, stack/templates/ingress.yaml, stack/templates/oidc_proxy.yaml, stack/tests/ingress_test.yaml, stack/tests/oidc_test.yaml, stack/values.yaml
Added for backwards compatability. When we remove the nginx annotations in the next PRs, we will need the skipAuth values.yaml to still work with the oauth2_proxy flags.
* #150 
* #152
=> fix: broken oauth2_proxy flags; change the behavior of oauth2_proxy to be used as proxy

stack/templates/oidc_proxy.yaml, stack/tests/oidc_test.yaml
All the upstreams need a trailing slash to simulate the pathprefix routing type. Checks if it is using "Exact" path type and omits the trailing slash.
* https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#upstreams-configuration
=> fix: trailing slash on upstreams

stack/templates/oidc_proxy.yaml, stack/tests/oidc_test.yaml
Fixes a bug where if people used `/` as their PathPrefix, it would lead to a double trailing slash in the upstream flag.
=> fix: double slash when users add a trailing slash

argo-workflows-rbac/Chart.yaml, argo-workflows-rbac/README.md, argo-workflows-rbac/templates/rbac.yaml, argo-workflows-rbac/values.schema.json, argo-workflows-rbac/values.yaml
This chart allows us to create a default clusterrole permitting single-namespaced Argo Workflow installation to access Argo Workflow templates (they are cluster scoped)
=> feat: Argo workflows RBAC chart

stack/templates/oidc_proxy.yaml
Fixes an issue with the OIDC proxy being configured for ingresses that are marked as disabled. OIDC proxy shouldn't use upstreams for disabled ingresses to avoid path collisions by accident.
=> fix: issue where oidc proxy is configured on disabled ingresses

stack/templates/deployment.yaml, stack/tests/deployment_test.yaml
Images for sidecars can only be specified with a full URI string which means the argus docker builder won't change the tag when it updates other image tags. We need to be able to specify it as a separate field like we do for the main container and init containers
=> feat: allow image tag to be specified separately for sidecars

stack/Chart.yaml
This is for fixing the [release](https://github.com/chanzuckerberg/argo-helm-charts/actions/runs/12798869845/job/35684615202).
=> fix: bump argus dependency

stack/templates/cronjob.yaml, stack/tests/cronjob_test.yaml
Currently adding annotation for eks role for cronjob is wrong, see [here](https://argo.dev.platform.si.czi.technology/applications/argocd/argus-rdev-e54afa8b?resource=&node=%2FServiceAccount%2Fcore-platform-rdev%2Fargus-rdev-e54afa8b-stack-syncawssecretmanager%2F0).
```
annotations:
eks.amazonaws.com/role-arn: 'arn:aws:iam::471112759938:role/argo_root_core_platform_infra_dev_eks'
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
labels:
app.kubernetes.io/instance: argus-rdev-e54afa8b
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: stack
app.kubernetes.io/service: argus-rdev-e54afa8b-stack-syncawssecretmanager
app.kubernetes.io/version: 1.16.0
argocd.argoproj.io/instance: argus-rdev-e54afa8b
helm.sh/chart: stack-2.5.2
name: …
```
=> fix: fixed whitespace for adding annotations

.release-please-manifest.json, release-please-config.json, sso-secret/README.md, sso-secret/templates/secret.yaml, sso-secret/values.schema.json, sso-secret/values.yaml
[CCIE-4347]
Adds the ability to pass a custom secret store. This chart is used in an `argo-workflows` deployment.
[CCIE-4347]: https://czi.atlassian.net/browse/CCIE-4347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Allow secret store customization

argo-project/.helmignore, argo-project/Chart.yaml, argo-project/Makefile, argo-project/README.md, argo-project/templates/project.yaml, argo-project/tests/project.yaml, argo-project/values.schema.json, argo-project/values.yaml, release-please-config.json
Adds a helm chart for an ArgoCD project. This will be used in conjunction with an ApplicationSet in argus-infra-stacks so we have a project to deploy all our cluster-specific addons through Argo applicationsets.
* https://github.com/chanzuckerberg/argus-infra-stacks/pull/674
=> feat: helm chart for argocd projects

grafana/templates/grafana.yaml, grafana/templates/sso-secret.yaml
Current configuration is limited to one, due to a single grafana-sso-secret. This PR ties the name of the secret to the name of the grafana deployed. Default grafanaName is `grafana`, so existing installs are not affected.
=> feat: Support multiple grafanas in the same namespace

argus-config/templates/context_configmap.yaml
Sometimes the git short SHA is all numbers. The configmap only takes string/string.
=> fix: quote the argus context values

grafana/templates/grafana.yaml
Since there's a default, we don't need the if statement anymore
=> fix: Remove if statement for allow_embedding

grafana/templates/grafana.yaml
This is the current manifest:
```
apiVersion: v1
data:
grafana.ini: >+
...
[grafana.ini]
security = allow_embedding = "true"
...
```
I want `security` to be the section and `allow_embedding` to be the key.
=> fix: Remove grafana.ini key

loki-monitoring/templates/alert_groups.yaml
Addressed: 
```
The GrafanaAlertRuleGroup "cw-loki-alerts" is invalid: 
* spec.rules[1].for: Required value
* spec.rules[2].for: Required value
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```
=> fix: Fix loki monitoring alertgroup

schema.mk, stack/README.md, stack/tests/deployment_test.yaml, stack/values.schema.json, stack/values.yaml
Biohub needs to be able to mount a volume snapshot but we still need to create the pvc for it. 
Docs:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#create-persistent-volume-claim-from-volume-snapshot
=> feat: Add volume snapshot support for pvc
